apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-api
  labels:
    nome: nest
spec:
  selector:
    matchLabels:
      nome: nest
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        nome: nest
    spec:
    
      containers: 
       - name: nest
         image: default 
         ports:
          - containerPort: 3000
         env:
           - name: HOST
             valueFrom:
              secretKeyRef:
                name: dbhost
                key: HOST
           - name: DBPORT
             valueFrom:
              secretKeyRef:
                name: dbport
                key: DBPORT
           - name: USER
             valueFrom:
              secretKeyRef:
                name: dbuser
                key: USER
           - name: PASSWORD
             valueFrom:
              secretKeyRef:
                name: dbpassword
                key: PASSWORD
           - name: DBNAME
             valueFrom:
              secretKeyRef:
                name: dbname
                key: DBNAME
           - name: PORT
             valueFrom:
              secretKeyRef:
                name: port
                key: PORT
         livenessProbe:
           httpGet:
             path: /health
             port: 3000
           initialDelaySeconds: 60
           periodSeconds: 5
      restartPolicy: Always
