apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-api
  labels:
    nome: nest
spec:
  selector:
    matchLabels:
      nome: nest
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        nome: nest
    spec:
    
      containers: 
       - name: nest
         image: default 
         ports:
          - containerPort: 3000
         env:
           - name: DB_HOST
             valueFrom:
              secretKeyRef:
                name: dbhost
                key: HOST
           - name: DB_PORT
             valueFrom:
              secretKeyRef:
                name: dbport
                key: DBPORT
           - name: DB_USERNAME
             valueFrom:
              secretKeyRef:
                name: dbuser
                key: USER
           - name: DB_PASSWORD
             valueFrom:
              secretKeyRef:
                name: dbpassword
                key: PASSWORD
           - name: DB_DATABASE
             valueFrom:
              secretKeyRef:
                name: dbname
                key: DBNAME
           - name: JWT_SECRET
             valueFrom:
              secretKeyRef:
                name: jwt
                key: JWTSECRET
         livenessProbe:
           httpGet:
             path: /health
             port: 3000
           initialDelaySeconds: 60
           periodSeconds: 5
      restartPolicy: Always
